// Autogenerated by MrShader
// Source: test.glsl

#ifndef _TEST_SHADER_H
#define _TEST_SHADER_H

#ifdef __cplusplus
constexpr const char* TEST_SHADER_VERTEX = 
#else
static const char* TEST_SHADER_VERTEX = 
#endif
	"#version 330 core\n"
	"layout(location = 0) in vec3 vs_pos;\n"
	"layout(location = 1) in vec3 vs_color;\n"
	"\n"
	"out vec3 fs_color;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tgl_Position = vec4(vs_pos, 1.0);\n"
	"\tfs_color = vs_color;\n"
	"}\n"
	"\n";

#ifdef __cplusplus
constexpr const char* TEST_SHADER_FRAGMENT = 
#else
static const char* TEST_SHADER_FRAGMENT = 
#endif
	"#version 330 core\n"
	"out vec4 frag_color;\n"
	"in vec3 fs_color;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tfrag_color = vec4(fs_color, 1.0);\n"
	"}\n";

#endif
