----------------------------------------
-- CHANGE THESE FOR YOUR OWN PROJECTS --
----------------------------------------
project = "sandbox"
starrydir = "."
builddir = "build"
assetsdir = "assets"

imgui_enabled = true
bfd_enabled = true
gen_compile_commands = true

srcs = {
	"sandbox/src/main.cpp",
	"sandbox/src/debug_mode.cpp",
	"sandbox/src/hello_triangle.cpp",
}

includes = {
	"sandbox/src"
}

-----------------------
-- ACTUAL BUILD CRAP --
-----------------------
io.write("Starry3D auto configurator 3000++\n")

io.write("Compile mode (debug/release): ")
compmode = io.read("*l")

io.write("Target platform (windows/linux): ")
platform = io.read("*l")

io.write("Use a sanitizer? (e.g. 'address' for asan, press enter to not use one): ")
sanitize = io.read("*l")

io.write("\nGenerating...\n")

---------------------------------------------------------------------
-- GETTING THE CRAP INFORMATION SO IT CAN ACTUALLY GENERATE FRFRFR --
---------------------------------------------------------------------

compiler = "clang++"
if platform == "windows" then
	compiler = "x86_64-w64-mingw32-g++"
end

cflags = "-std=c++17 -Wall -Wextra -Wpedantic -g "

-- includes
cflags = cflags ..
	" -I"..starrydir.."/src"..
	" -I"..starrydir.."/thirdparty"..
	" -I"..starrydir.."/thirdparty/libtrippin"..
	" -I"..starrydir.."/thirdparty/glfw/include"..
	" -I"..starrydir.."/thirdparty/stb"..
	" -I"..starrydir.."/thirdparty/whereami/src"

if imgui_enabled then
	cflags = cflags ..
		" -I"..starrydir.."/thirdparty/imgui"..
		" -I"..starrydir.."/thirdparty/imgui/backends"
end

-- custom includes
for _, include in ipairs(includes) do
	cflags = cflags.." -I"..include
end

-- source files
srcsfrfr = {
	-- libtrippin
	starrydir.."/thirdparty/libtrippin/trippin/collection.cpp",
	starrydir.."/thirdparty/libtrippin/trippin/common.cpp",
	starrydir.."/thirdparty/libtrippin/trippin/iofs.cpp",
	starrydir.."/thirdparty/libtrippin/trippin/log.cpp",
	starrydir.."/thirdparty/libtrippin/trippin/math.cpp",
	starrydir.."/thirdparty/libtrippin/trippin/memory.cpp",
	starrydir.."/thirdparty/libtrippin/trippin/string.cpp",

	-- starry3d
	starrydir.."/src/st_common.cpp",
	starrydir.."/src/st_window.cpp",
	starrydir.."/src/st_render.cpp",
}

-- imgui
if imgui_enabled then
	table.insert(srcsfrfr, starrydir.."/src/st_imgui.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/imgui.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/imgui_widgets.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/imgui_tables.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/imgui_draw.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/imgui_demo.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/backends/imgui_impl_glfw.cpp")
	table.insert(srcsfrfr, starrydir.."/thirdparty/imgui/backends/imgui_impl_opengl3.cpp")
end

-- custom sources
for _, src in ipairs(srcs) do
	table.insert(srcsfrfr, src)
end

if platform == "windows" then
	cflags = cflags.." -DST_WINDOWS"
else
	cflags = cflags.." -DST_LINUX"
end

-- ldflags
-- idfk why libglfw3.a goes into the src folder it just does
ldflags = "-Lbuild/glfw/src"

if platform == "windows" then
	ldflags = ldflags.." -lglfw3 -lopengl32 -lgdi32 -lwinmm -lcomdlg32 -lole32 -lpthread -lstdc++"
else
	ldflags = ldflags.." -lglfw3 -lX11 -lXrandr -lGL -lXinerama -lm -lpthread"
	if bfd_enabled then
		ldflags = ldflags.." -lbfd"
		cflags = cflags.." -DBACKWARD_HAS_BFD=1"
	end
	ldflags = ldflags.." -ldl -lrt -lstdc++"
end

-- man.
if compmode == "debug" then
	cflags = cflags.." -O0 -DDEBUG -D_DEBUG"
else
	cflags = cflags.." -O2"
end

if sanitize ~= "" then
	cflags = cflags.." -fsanitize="..sanitize
	ldflags = ldflags.." -fsanitize="..sanitize
end

------------------------------------------------
-- GENERATE THE BUILD FILES FRFRFR ONG NO CAP --
------------------------------------------------

local f = io.open("build.ninja", "w")
assert(f)

f:write("# Autogenerated by configure.lua. You probably shouldn't edit this.\n")
f:write("cxx = "..compiler.."\n")
f:write("cflags = "..cflags.."\n")
f:write("ldflags = "..ldflags.."\n")

f:write("\nrule glfw_build\n")
-- TODO windows cross compiling
f:write("  command = "..
		"mkdir "..builddir.."/glfw -p && "..
		"cmake -S "..starrydir.."/thirdparty/glfw -B "..builddir.."/glfw -D GLFW_LIBRARY_TYPE=STATIC -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_TESTS=OFF && "..
		"cd "..builddir.."/glfw && "..
		"make"
)
f:write("\n  description = Compiling GLFW\n")


f:write("\nrule compile\n")
f:write("  command = $cxx $cflags -c $in -o $out\n")
f:write("  description = Compiling $in\n")

f:write("\nrule link\n")
f:write("  command = $cxx $in $ldflags -o $out\n")
f:write("  description = Linking $out\n")

f:write("\nrule copy_assets\n")
f:write("  command = mkdir "..builddir.."/bin/"..assetsdir.." cp -r "..assetsdir.."/* "..builddir.."/bin/"..assetsdir.."\n")
f:write("  description = Copying assets folder\n")

-- man
f:write("\nbuild "..builddir.."/glfw/libglfw3.a: glfw_build\n")

-- build crap :)
for _, src in ipairs(srcsfrfr) do
	f:write("build "..builddir.."/obj/"..src:gsub("%.cpp", ".o"):gsub("/", "_")..": compile "..src.."\n")
end

-- link crap :)
f:write("\nbuild "..builddir.."/bin/"..project..": link ")
for _, src in ipairs(srcsfrfr) do
	f:write(builddir.."/obj/"..src:gsub("%.cpp", ".o"):gsub("/", "_").." ")
end
f:write("| "..builddir.."/glfw/libglfw3.a\n")

f:write("\ndefault "..builddir.."/bin/"..project.."\n")

f:close()

----------------
-- ITS JOEVER --
----------------

io.write("Generated build.ninja; run `ninja` to compile\n")

if gen_compile_commands then
	os.execute("ninja -t compdb > compile_commands.json")
end
