#!/usr/bin/sh
# this script is just a basic wrapper bcuz im lazy
# you can see why the ?deargod? in engineer.lua
# i love lua
if [ "$#" -eq 0 ]; then
    lua engineer.lua ?deargod? help
else
    lua engineer.lua ?deargod? $@
fi
