#!/usr/bin/sh
# this script is just a basic wrapper bcuz im lazy
# lua modules are obnoxious and idk how to fix this properly
if [ "$#" -eq 0 ]; then
    lua engineer.lua ?shutup help
else
    lua engineer.lua ?shutup $@
fi
