// Autogenerated by MrShadificator
// Source: ../src/shader/basic.glsl

#ifndef _st_BASIC_SHADER_H
#define _st_BASIC_SHADER_H

namespace st {

constexpr const char* BASIC_SHADER_VERTEX = 
	"#version 330 core\n"
	"layout (location = 0) in vec3 position;\n"
	"layout (location = 1) in vec4 color;\n"
	"\n"
	"out vec4 out_color;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tgl_Position = vec4(position, 1.0);\n"
	"\tout_color = color;\n"
	"}\n"
	"\n";

constexpr const char* BASIC_SHADER_FRAGMENT = 
	"#version 330 core\n"
	"in vec4 out_color;\n"
	"\n"
	"out vec4 FragColor;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tFragColor = vec4(1, 1, 1, 1);\n"
	"}\n";

}

#endif
