function get_shader_srcs(shadersrc)
	local shaderf = io.open(shadersrc, "r")
	if shaderf == nil then
		error("couldn't open file " .. shadersrc, 1)
		return {"", ""}
	end

	local lines = shaderf:lines()
	local cursrc = ""
	local vertsrc = {}
	local fragsrc = {}
	for line in lines do
		if line == "#vertex" then
			cursrc = "vert"
		elseif line == "#fragment" then
			cursrc = "frag"
		else
			if cursrc == "vert" then table.insert(vertsrc, line)
			elseif cursrc == "frag" then table.insert(fragsrc, line)
			else warn("line not in a vertex or fragment shader") end
		end
	end

	io.close(shaderf)
	return {vertsrc, fragsrc}
end

function make_header(vertlines, fraglines, dest, strname)
	local headerf = io.open(dest, "w")
	if headerf == nil then
		error("couldn't open file " .. dest, 1)
	end

	-- usual header stuff
	local guard = "_" .. strname .. "_H"
	headerf:write("// Autogenerated by MrShadificator\n")
	headerf:write("// Source: " .. arg[1] .. "\n\n")
	headerf:write("#ifndef " .. guard .. "\n")
	headerf:write("#define " .. guard .. "\n\n")

	-- man
	headerf:write("#define " .. strname .. "_VERTEX \\\n")
	for _, line in pairs(vertlines) do
		-- TODO this will break
		line = line:gsub("\t", "\\t")
		line = line:gsub("\"", "\\\"")

		headerf:write("\t\"" .. line .. "\\n\" \\\n")
	end

	headerf:write("\n#define " .. strname .. "_FRAGMENT \\\n")
	for _, line in pairs(fraglines) do
		-- TODO this will break
		line = line:gsub("\t", "\\t")
		line = line:gsub("\"", "\\\"")

		headerf:write("\t\"" .. line .. "\\n\" \\\n")
	end

	-- more usual header stuff
	headerf:write("\n#endif\n")

	io.close(headerf)
end

if #arg < 3 then
	print("Usage: [shader source] [header destination] [string name]")
else
	local srcs = get_shader_srcs(arg[1])
	make_header(srcs[1], srcs[2], arg[2], arg[3])
end
