// Autogenerated by MrShader
// Source: starry/shader/basic.glsl

#ifndef _ST_BASIC_SHADER_H
#define _ST_BASIC_SHADER_H

#ifdef __cplusplus
constexpr const char* ST_BASIC_SHADER_VERTEX = 
#else
static const char* ST_BASIC_SHADER_VERTEX = 
#endif
	"#version 430 core\n"
	"layout (location = 0) in vec3 vs_position;\n"
	"layout (location = 1) in vec4 vs_color;\n"
	"\n"
	"out vec4 fs_color;\n"
	"\n"
	"uniform mat4 u_model;\n"
	"uniform mat4 u_view;\n"
	"uniform mat4 u_projection;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tgl_Position = u_projection * u_view * u_model * vec4(vs_position, 1.0);\n"
	"\tfs_color = vs_color;\n"
	"}\n"
	"\n";

#ifdef __cplusplus
constexpr const char* ST_BASIC_SHADER_FRAGMENT = 
#else
static const char* ST_BASIC_SHADER_FRAGMENT = 
#endif
	"#version 430 core\n"
	"in vec4 fs_color;\n"
	"\n"
	"out vec4 frag_color;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tfrag_color = fs_color;\n"
	"}\n";

#endif
