package starry

import lua "../thirdparty/luajit"
import "core:c"
import "core:fmt"

init_lua :: proc()
{
	global.lua = lua.L_newstate()
	L := global.lua
	if L == nil {
		fmt.panicf("couldn't initialize Lua")
	}

	lua.atpanic(L, proc "c" (L: ^lua.State) -> c.int
	{
		context = global.ctx
		fmt.printfln("lua panic: %s", lua.tostring(L, -1))
		lua.L_traceback(L, L, nil, 1)
		fmt.printfln("%s", lua.tostring(L, -1))
		panic("aborting")
	})

	lua.L_openlibs(L)
	// prevent a chicken & egg situation if i have to delete the autogenerated files so that i
	// can fix the bindgen since they're all the same package
	when #exists("lua_app.odin") || DISABLE_DEV_TOOLS {
		lua_open_app(L)
	}
	lua_run(L, #load("../lualibs/boot.lua"), "lualibs/boot.lua")
	lua_run(L, #load("../lualibs/table.lua"), "lualibs/table.lua")
	lua_run(L, #load("../lualibs/math.lua"), "lualibs/table.lua")
	lua_run(L, #load("../lualibs/gpu.lua"), "lualibs/gpu.lua")
}

free_lua :: proc()
{
	L := global.lua
	lua.close(L)
}

lua_run :: proc(L: ^lua.State, code: []byte, path: cstring = "unknown script") -> bool
{
	if lua.L_loadbuffer(L, raw_data(code), len(code), path) != lua.OK {
		lua_error(L)
		return false
	}

	if lua.pcall(L, 0, 0, 0) != i32(lua.OK) {
		lua_error(L)
	}
	return true
}

lua_error :: proc(L: ^lua.State)
{
	err := lua.tostring(L, -1)
	fmt.println(err)
	lua.pop(L, 1)
}

Lua_Variant :: union {
	lua.Number,
	lua.Integer,
	string,
	cstring,
	b32,
	rawptr,
}

// expects the function to have no returns
call_lua_function :: proc(
	L: ^lua.State,
	func_name: cstring,
	args: ..Lua_Variant,
	can_be_nil := false,
) -> (
	ok: bool,
)
{
	lua.getglobal(L, func_name)

	if !lua.isfunction(L, -1) {
		if can_be_nil && lua.isnil(L, -1) {
			lua.pop(L, 1)
			return true
		}
		lua.pop(L, 1)
		return false
	}

	for arg in args {
		switch v in arg {
		case lua.Number:
			lua.pushnumber(L, v)
		case lua.Integer:
			lua.pushinteger(L, v)
		case string:
			lua.pushlstring(L, cast(cstring)raw_data(v), c.size_t(len(v)))
		case cstring:
			lua.pushstring(L, v)
		case b32:
			lua.pushboolean(L, v)
		case rawptr:
			lua.pushlightuserdata(L, v)
		case:
			lua.pushnil(L)
		}
	}

	if lua.pcall(L, c.int(len(args)), 0, 0) != i32(lua.OK) {
		lua_error(L)
		return false
	}

	return true
}
