package starry

import "base:intrinsics"
import "base:runtime"
import "core:fmt"
import "core:os"

bindgen :: proc()
{
	defer free_all(context.temp_allocator)

	fmt.println("writing to starry/lua_app.odin, lualibs/app.lua")
	err := bindgen_module_app()
	if err != nil {
		fmt.panicf("couldn't bind module app: %s", os.error_string(err))
	}
}

Module_Bindgen_State :: struct {
	odinf:                ^os.File,
	name:                 string,
	func_names:           [dynamic]string,
	string_to_enum_funcs: map[string]string,
}

bindgen_module_app :: proc() -> (err: os.Error)
{
	// setup module
	mod := Module_Bindgen_State{}
	mod.name = "app"
	mod.odinf = os.open("starry/lua_app.odin", {.Write, .Create}) or_return
	mod.func_names = make([dynamic]string)
	mod.string_to_enum_funcs = make(map[string]string)

	defer os.close(mod.odinf)
	defer delete(mod.func_names)
	defer delete(mod.string_to_enum_funcs)

	// config
	bindgen_add_string_to_enum_func(&mod, "Key", key_from_string)
	bindgen_add_string_to_enum_func(&mod, "MouseButton", mouse_button_from_string)

	bindgen_module_start(&mod) or_return
	bindgen_write_function(&mod, now_secs) or_return
	bindgen_write_function(&mod, delta_time) or_return
	bindgen_write_function(&mod, is_closing) or_return
	bindgen_write_function(&mod, is_headless) or_return
	bindgen_write_function(&mod, app_dir, lua_name = "dir") or_return
	bindgen_write_function(&mod, mouse_pos) or_return
	bindgen_write_function(&mod, delta_mouse_pos) or_return
	bindgen_write_function(&mod, key_just_pressed) or_return
	bindgen_write_function(&mod, key_held) or_return
	bindgen_write_function(&mod, key_just_released) or_return
	bindgen_write_function(&mod, key_not_pressed) or_return
	bindgen_write_function(&mod, mouse_just_pressed) or_return
	bindgen_write_function(&mod, mouse_held) or_return
	bindgen_write_function(&mod, mouse_just_released) or_return
	bindgen_write_function(&mod, mouse_not_pressed) or_return
	bindgen_write_function(&mod, frame_sizef, lua_name = "frame_size") or_return
	bindgen_write_function(&mod, aspect_ratio) or_return
	bindgen_write_function(&mod, high_dpi) or_return
	bindgen_write_function(&mod, scale_factor) or_return
	bindgen_write_function(&mod, lock_mouse) or_return
	bindgen_write_function(&mod, is_mouse_locked) or_return
	bindgen_write_function(&mod, request_quit) or_return
	bindgen_write_function(&mod, cancel_quit) or_return
	bindgen_write_function(&mod, set_title) or_return
	bindgen_module_end(&mod) or_return

	return nil
}

bindgen_module_start :: proc(mod: ^Module_Bindgen_State) -> (err: os.Error)
{
	fmt.fprintfln(mod.odinf, "// autogenerated!")
	fmt.fprintfln(mod.odinf, "package starry")
	fmt.fprintfln(mod.odinf, "")
	fmt.fprintfln(mod.odinf, `import "core:c"`)
	fmt.fprintfln(mod.odinf, `import lua "../thirdparty/luajit"`)
	fmt.fprintfln(mod.odinf, "")

	return nil
}

bindgen_module_end :: proc(mod: ^Module_Bindgen_State) -> (err: os.Error)
{
	fmt.fprintfln(mod.odinf, `lua_open_%s :: proc "c" (L: ^lua.State)`, mod.name)
	fmt.fprintfln(mod.odinf, "{{")
	fmt.fprintfln(mod.odinf, "\tmod := []lua.L_Reg{{")
	for func_name in mod.func_names {
		fmt.fprintfln(
			mod.odinf,
			"\t\t{{name = \"%s\", func = %s}},",
			func_name,
			bindgen_wrapper_name(func_name, mod.name),
		)
	}
	fmt.fprintfln(mod.odinf, "\t\t{{name = nil, func = nil}},")
	fmt.fprintfln(mod.odinf, "\t}}")
	fmt.fprintfln(mod.odinf, "\tlua.L_openlib(L, \"%s\", raw_data(mod), 0)", mod.name)
	fmt.fprintfln(mod.odinf, "\t")
	fmt.fprintfln(mod.odinf, "}}")

	return nil
}

// this function only exists for #caller_expression
bindgen_add_string_to_enum_func :: proc(
	mod: ^Module_Bindgen_State,
	type_name: string,
	p: proc(s: string) -> $T,
	call_name: string = #caller_expression(p),
)
{
	mod.string_to_enum_funcs[type_name] = call_name
}

bindgen_wrapper_name :: proc(src: string, mod: string) -> string
{
	return fmt.tprintf("lua_%s_%s", mod, src)
}

bindgen_write_function :: proc(
	mod: ^Module_Bindgen_State,
	p: $T,
	lua_name: string = #caller_expression(p),
	call_name: string = #caller_expression(p),
) -> (
	err: os.Error,
) where intrinsics.type_is_proc(T)
{
	append(&mod.func_names, lua_name)

	proc_ti := type_info_of(T).variant.(runtime.Type_Info_Procedure)
	if proc_ti.variadic {
		unimplemented("binding variadic functions")
	}

	fmt.fprintfln(mod.odinf, `@(private = "file")`)
	fmt.fprintfln(
		mod.odinf,
		`%s :: proc "c" (L: ^lua.State) -> c.int`,
		bindgen_wrapper_name(lua_name, mod.name),
	)
	fmt.fprintfln(mod.odinf, "{{")
	fmt.fprintfln(mod.odinf, "\tcontext = global.ctx")

	if proc_ti.params != nil {
		bindgen_write_params(mod, proc_ti)
	}
	bindgen_write_function_call(mod, proc_ti, call_name)
	if proc_ti.results != nil {
		bindgen_write_returns(mod, proc_ti)
	} else {
		fmt.fprintfln(mod.odinf, "\treturn 0")
	}

	fmt.fprintfln(mod.odinf, "}}")
	fmt.fprintfln(mod.odinf, "")

	return nil
}

bindgen_write_params :: proc(mod: ^Module_Bindgen_State, proc_ti: runtime.Type_Info_Procedure)
{
	// why is this a goofy soa thing
	params := proc_ti.params.variant.(runtime.Type_Info_Parameters)
	assert(len(params.names) == len(params.types))

	for i in 0 ..< len(params.names) {
		param_name := params.names[i]
		param_type := params.types[i]

		bindgen_write_function_arg(mod, param_type, i + 1)
	}
}

bindgen_write_function_arg :: proc(
	mod: ^Module_Bindgen_State,
	param_type: ^runtime.Type_Info,
	i: int,
)
{
	#partial switch v in param_type.variant {
	case runtime.Type_Info_Integer:
		fmt.fprintfln(mod.odinf, "\targ%d := lua.L_checkinteger(L, %d)", i, i)

	case runtime.Type_Info_Float:
		fmt.fprintfln(mod.odinf, "\targ%d := lua.L_checknumber(L, %d)", i, i)

	case runtime.Type_Info_String:
		fmt.fprintfln(mod.odinf, "\targ%d_len: c.size_t", i)
		fmt.fprintfln(
			mod.odinf,
			"\targ%d_cstr := lua.L_checkstring(L, %d, &arg%d_len)",
			i,
			i,
			i,
		)
		fmt.fprintfln(
			mod.odinf,
			"\targ%d := string((cast([^]byte)arg%d_cstr)[:arg%d_len])",
			i,
			i,
			i,
		)

	case runtime.Type_Info_Boolean:
		fmt.fprintfln(mod.odinf, "\targ%d := bool(lua.L_checkinteger(L, %d))", i, i)

	// why
	case runtime.Type_Info_Named:
		#partial switch vv in v.base.variant {
		case runtime.Type_Info_Enum:
			converter_proc, ok := mod.string_to_enum_funcs[v.name]
			if !ok {
				fmt.panicf("no string -> enum converter for %s", param_type)
			}

			fmt.fprintfln(
				mod.odinf,
				"\targ%d := %s(string(lua.L_checkstring(L, %d)))",
				i,
				converter_proc,
				i,
			)
		}

	case:
		unimplemented(fmt.tprintf("%#v", v))
	}
}

bindgen_write_function_call :: proc(
	mod: ^Module_Bindgen_State,
	proc_ti: runtime.Type_Info_Procedure,
	name: string,
)
{
	fmt.fprintf(mod.odinf, "\t")

	if proc_ti.results != nil {
		returns := proc_ti.results.variant.(runtime.Type_Info_Parameters)
		for _, i in returns.names {
			fmt.fprintf(mod.odinf, "res%i", i + 1)
			if i < len(returns.names) - 1 {
				fmt.fprintf(mod.odinf, ", ")
			}

			fmt.fprintf(mod.odinf, " := ")
		}
	}

	fmt.fprintf(mod.odinf, "%s(", name)

	if proc_ti.params != nil {
		params := proc_ti.params.variant.(runtime.Type_Info_Parameters)
		for _, i in params.names {
			fmt.fprintf(mod.odinf, "arg%d, ", i + 1)
		}
	}

	fmt.fprintln(mod.odinf, ")")
}

bindgen_write_returns :: proc(mod: ^Module_Bindgen_State, proc_ti: runtime.Type_Info_Procedure)
{
	// why is this a goofy soa thing
	returns := proc_ti.results.variant.(runtime.Type_Info_Parameters)
	assert(len(returns.names) == len(returns.types))

	for i in 0 ..< len(returns.names) {
		ret_name := returns.names[i]
		ret_type := returns.types[i]

		#partial switch v in ret_type.variant {
		case runtime.Type_Info_Integer:
			fmt.fprintfln(mod.odinf, "\tlua.pushinteger(L, lua.Integer(res%d))", i + 1)

		case runtime.Type_Info_Float:
			fmt.fprintfln(mod.odinf, "\tlua.pushnumber(L, lua.Number(res%d))", i + 1)

		case runtime.Type_Info_String:
			fmt.fprintfln(
				mod.odinf,
				"\tlua.pushlstring(L, cast(cstring)raw_data(res%d), c.size_t(len(res%d)))",
				i + 1,
				i + 1,
			)

		case runtime.Type_Info_Boolean:
			fmt.fprintfln(mod.odinf, "\tlua.pushboolean(L, b32(res%d))", i + 1)

		case runtime.Type_Info_Array:
			fmt.fprintfln(mod.odinf, "\tlua.newtable(L)")

			switch v.count {
			case 2:
				fmt.fprintfln(mod.odinf, "\tlua.getglobal(L, \"Vec2\")")
				fmt.fprintfln(mod.odinf, "\tlua.setmetatable(L, -2)")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[0]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"x\")")
				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[1]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"y\")")

			case 3:
				fmt.fprintfln(mod.odinf, "\tlua.getglobal(L, \"Vec3\")")
				fmt.fprintfln(mod.odinf, "\tlua.setmetatable(L, -2)")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[0]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"x\")")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[1]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"y\")")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[2]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"z\")")

			case 4:
				fmt.fprintfln(mod.odinf, "\tlua.getglobal(L, \"Vec4\")")
				fmt.fprintfln(mod.odinf, "\tlua.setmetatable(L, -2)")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[0]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"x\")")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[1]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"y\")")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[2]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"z\")")

				fmt.fprintfln(
					mod.odinf,
					"\tlua.pushnumber(L, lua.Number(res%d[3]))",
					i + 1,
				)
				fmt.fprintfln(mod.odinf, "\tlua.setfield(L, -2, \"w\")")
			case:
				unimplemented()
			}

		case:
			unimplemented(fmt.tprintf("%#v", v))
		}
	}

	fmt.fprintfln(mod.odinf, "\treturn %d", len(returns.names))
}
