package starry

import "base:intrinsics"
import "base:runtime"
import "core:fmt"
import "core:os"

bindgen :: proc()
{
	defer free_all(context.temp_allocator)

	fmt.println("writing to starry/lua_app.odin, lualibs/app.lua")
	err := bindgen_module_app()
	if err != nil {
		fmt.panicf("couldn't bind module app: %s", os.error_string(err))
	}
}

Module_Bindgen_State :: struct {
	odinf:      ^os.File,
	func_names: [dynamic]string,
	name:       string,
}

bindgen_module_app :: proc() -> (err: os.Error)
{
	mod := Module_Bindgen_State{}
	mod.odinf = os.open("starry/lua_app.odin", {.Write, .Create}) or_return
	mod.func_names = make([dynamic]string)
	mod.name = "app"

	defer os.close(mod.odinf)
	defer delete(mod.func_names)

	bindgen_module_start(&mod) or_return
	bindgen_write_function(&mod, now_in_seconds) or_return
	bindgen_write_function(&mod, delta_time) or_return
	bindgen_write_function(&mod, is_closing) or_return
	bindgen_write_function(&mod, is_headless) or_return
	bindgen_write_function(&mod, app_dir, lua_name = "dir") or_return
	// bindgen_write_function(&mod, mouse_position) or_return
	// bindgen_write_function(&mod, delta_mouse_position) or_return
	// bindgen_write_function(&mod, is_key_just_pressed) or_return
	// bindgen_write_function(&mod, is_key_held) or_return
	// bindgen_write_function(&mod, is_key_just_released) or_return
	// bindgen_write_function(&mod, is_key_not_pressed) or_return
	// bindgen_write_function(&mod, is_mouse_button_just_pressed) or_return
	// bindgen_write_function(&mod, is_mouse_button_held) or_return
	// bindgen_write_function(&mod, is_mouse_button_just_released) or_return
	// bindgen_write_function(&mod, is_mouse_button_just_released) or_return
	// bindgen_write_function(&mod, is_mouse_button_not_pressed) or_return
	// bindgen_write_function(&mod, framebuffer_sizef, name = "framebuffer_size") or_return
	bindgen_write_function(&mod, aspect_ratio) or_return
	bindgen_write_function(&mod, is_high_dpi) or_return
	bindgen_write_function(&mod, scale_factor) or_return
	bindgen_write_function(&mod, lock_mouse) or_return
	bindgen_write_function(&mod, is_mouse_locked) or_return
	bindgen_write_function(&mod, request_quit) or_return
	bindgen_write_function(&mod, cancel_quit) or_return
	bindgen_write_function(&mod, set_title) or_return
	bindgen_module_end(&mod) or_return

	return nil
}

bindgen_module_start :: proc(mod: ^Module_Bindgen_State) -> (err: os.Error)
{
	fmt.fprintfln(mod.odinf, "// autogenerated!")
	fmt.fprintfln(mod.odinf, "package starry")
	fmt.fprintfln(mod.odinf, "")
	fmt.fprintfln(mod.odinf, `import "core:c"`)
	fmt.fprintfln(mod.odinf, `import lua "../thirdparty/luajit"`)
	fmt.fprintfln(mod.odinf, "")

	return nil
}

bindgen_module_end :: proc(mod: ^Module_Bindgen_State) -> (err: os.Error)
{
	fmt.fprintfln(mod.odinf, `lua_open_%s :: proc "c" (L: ^lua.State)`, mod.name)
	fmt.fprintfln(mod.odinf, "{{")
	fmt.fprintfln(mod.odinf, "\tmod := []lua.L_Reg{{")
	for func_name in mod.func_names {
		fmt.fprintfln(
			mod.odinf,
			"\t\t{{name = \"%s\", func = %s}},",
			func_name,
			bindgen_wrapper_name(func_name, mod.name),
		)
	}
	fmt.fprintfln(mod.odinf, "\t\t{{name = nil, func = nil}},")
	fmt.fprintfln(mod.odinf, "\t}}")
	fmt.fprintfln(mod.odinf, "\tlua.L_openlib(L, \"%s\", raw_data(mod), 0)", mod.name)
	fmt.fprintfln(mod.odinf, "\t")
	fmt.fprintfln(mod.odinf, "}}")

	return nil
}

bindgen_wrapper_name :: proc(src: string, mod: string) -> string
{
	return fmt.tprintf("lua_%s_%s", mod, src)
}

bindgen_write_function :: proc(
	mod: ^Module_Bindgen_State,
	p: $T,
	lua_name: string = #caller_expression(p),
	call_name: string = #caller_expression(p),
) -> (
	err: os.Error,
) where intrinsics.type_is_proc(T)
{
	append(&mod.func_names, lua_name)

	proc_ti := type_info_of(T).variant.(runtime.Type_Info_Procedure)
	if proc_ti.variadic {
		unimplemented("binding variadic functions")
	}

	fmt.fprintfln(
		mod.odinf,
		`%s :: proc "c" (L: ^lua.State) -> c.int`,
		bindgen_wrapper_name(lua_name, mod.name),
	)
	fmt.fprintfln(mod.odinf, "{{")
	fmt.fprintfln(mod.odinf, "\tcontext = global.ctx")

	if proc_ti.params != nil {
		bindgen_write_params(mod, proc_ti)
	}
	bindgen_write_function_call(mod, proc_ti, call_name)
	if proc_ti.results != nil {
		bindgen_write_returns(mod, proc_ti)
	} else {
		fmt.fprintfln(mod.odinf, "\treturn 0")
	}

	fmt.fprintfln(mod.odinf, "}}")
	fmt.fprintfln(mod.odinf, "")

	return nil
}

bindgen_write_params :: proc(mod: ^Module_Bindgen_State, proc_ti: runtime.Type_Info_Procedure)
{
	// why is this a goofy soa thing
	params := proc_ti.params.variant.(runtime.Type_Info_Parameters)
	assert(len(params.names) == len(params.types))

	for i in 0 ..< len(params.names) {
		param_name := params.names[i]
		param_type := params.types[i]

		#partial switch v in param_type.variant {
		case runtime.Type_Info_Integer:
			fmt.fprintfln(
				mod.odinf,
				"\targ%d := lua.L_checkinteger(L, %d)",
				i + 1,
				i + 1,
			)

		case runtime.Type_Info_Float:
			fmt.fprintfln(
				mod.odinf,
				"\targ%d := lua.L_checknumber(L, %d)",
				i + 1,
				i + 1,
			)

		case runtime.Type_Info_String:
			fmt.fprintfln(mod.odinf, "\targ%d_len: c.size_t", i + 1)
			fmt.fprintfln(
				mod.odinf,
				"\targ%d_cstr := lua.L_checkstring(L, %d, &arg%d_len)",
				i + 1,
				i + 1,
				i + 1,
			)
			fmt.fprintfln(
				mod.odinf,
				"\targ%d := string((cast([^]byte)arg%d_cstr)[:arg%d_len])",
				i + 1,
				i + 1,
				i + 1,
			)

		case runtime.Type_Info_Boolean:
			fmt.fprintfln(
				mod.odinf,
				"\targ%d := bool(lua.L_checkinteger(L, %d))",
				i + 1,
				i + 1,
			)

		case:
			unimplemented()
		}
	}
}

bindgen_write_function_call :: proc(
	mod: ^Module_Bindgen_State,
	proc_ti: runtime.Type_Info_Procedure,
	name: string,
)
{
	fmt.fprintf(mod.odinf, "\t")

	if proc_ti.results != nil {
		returns := proc_ti.results.variant.(runtime.Type_Info_Parameters)
		for _, i in returns.names {
			fmt.fprintf(mod.odinf, "res%i", i + 1)
			if i < len(returns.names) - 1 {
				fmt.fprintf(mod.odinf, ", ")
			}

			fmt.fprintf(mod.odinf, " := ")
		}
	}

	fmt.fprintf(mod.odinf, "%s(", name)

	if proc_ti.params != nil {
		params := proc_ti.params.variant.(runtime.Type_Info_Parameters)
		for _, i in params.names {
			fmt.fprintf(mod.odinf, "arg%d, ", i + 1)
		}
	}

	fmt.fprintln(mod.odinf, ")")
}

bindgen_write_returns :: proc(mod: ^Module_Bindgen_State, proc_ti: runtime.Type_Info_Procedure)
{
	// why is this a goofy soa thing
	returns := proc_ti.results.variant.(runtime.Type_Info_Parameters)
	assert(len(returns.names) == len(returns.types))

	for i in 0 ..< len(returns.names) {
		ret_name := returns.names[i]
		ret_type := returns.types[i]

		#partial switch v in ret_type.variant {
		case runtime.Type_Info_Integer:
			fmt.fprintfln(mod.odinf, "\tlua.pushinteger(L, lua.Integer(res%d))", i + 1)

		case runtime.Type_Info_Float:
			fmt.fprintfln(mod.odinf, "\tlua.pushnumber(L, lua.Number(res%d))", i + 1)

		case runtime.Type_Info_String:
			fmt.fprintfln(
				mod.odinf,
				"\tlua.pushlstring(L, cast(cstring)raw_data(res%d), c.size_t(len(res%d)))",
				i + 1,
				i + 1,
			)

		case runtime.Type_Info_Boolean:
			fmt.fprintfln(mod.odinf, "\tlua.pushboolean(L, b32(res%d))", i + 1)

		case:
			unimplemented()
		}
	}

	fmt.fprintfln(mod.odinf, "\treturn %d", len(returns.names))
}
