// autogenerated!
package starry

import "core:c"
import lua "../thirdparty/luajit"

@(private = "file")
lua_app_now_in_seconds :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := now_secs()
	lua.pushnumber(L, lua.Number(res1))
	return 1
}

@(private = "file")
lua_app_delta_time :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := delta_time()
	lua.pushnumber(L, lua.Number(res1))
	return 1
}

@(private = "file")
lua_app_is_closing :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := is_closing()
	lua.pushboolean(L, b32(res1))
	return 1
}

@(private = "file")
lua_app_is_headless :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := is_headless()
	lua.pushboolean(L, b32(res1))
	return 1
}

@(private = "file")
lua_app_dir :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := app_dir()
	lua.pushlstring(L, cast(cstring)raw_data(res1), c.size_t(len(res1)))
	return 1
}

@(private = "file")
lua_app_aspect_ratio :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := aspect_ratio()
	lua.pushnumber(L, lua.Number(res1))
	return 1
}

@(private = "file")
lua_app_is_high_dpi :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := high_dpi()
	lua.pushboolean(L, b32(res1))
	return 1
}

@(private = "file")
lua_app_scale_factor :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := scale_factor()
	lua.pushnumber(L, lua.Number(res1))
	return 1
}

@(private = "file")
lua_app_lock_mouse :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	arg1 := bool(lua.L_checkinteger(L, 1))
	lock_mouse(arg1, )
	return 0
}

@(private = "file")
lua_app_is_mouse_locked :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	res1 := is_mouse_locked()
	lua.pushboolean(L, b32(res1))
	return 1
}

@(private = "file")
lua_app_request_quit :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	request_quit()
	return 0
}

@(private = "file")
lua_app_cancel_quit :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	cancel_quit()
	return 0
}

@(private = "file")
lua_app_set_title :: proc "c" (L: ^lua.State) -> c.int
{
	context = global.ctx
	arg1_len: c.size_t
	arg1_cstr := lua.L_checkstring(L, 1, &arg1_len)
	arg1 := string((cast([^]byte)arg1_cstr)[:arg1_len])
	set_title(arg1, )
	return 0
}

lua_open_app :: proc "c" (L: ^lua.State)
{
	mod := []lua.L_Reg{
		{name = "now_in_seconds", func = lua_app_now_in_seconds},
		{name = "delta_time", func = lua_app_delta_time},
		{name = "is_closing", func = lua_app_is_closing},
		{name = "is_headless", func = lua_app_is_headless},
		{name = "dir", func = lua_app_dir},
		{name = "aspect_ratio", func = lua_app_aspect_ratio},
		{name = "is_high_dpi", func = lua_app_is_high_dpi},
		{name = "scale_factor", func = lua_app_scale_factor},
		{name = "lock_mouse", func = lua_app_lock_mouse},
		{name = "is_mouse_locked", func = lua_app_is_mouse_locked},
		{name = "request_quit", func = lua_app_request_quit},
		{name = "cancel_quit", func = lua_app_cancel_quit},
		{name = "set_title", func = lua_app_set_title},
		{name = nil, func = nil},
	}
	lua.L_openlib(L, "app", raw_data(mod), 0)
	
}
