#version 430 core

// hardcoding my beloved
const vec2 IMAGE_SIZE = vec2(128, 96);
const vec2 CHAR_SIZE = vec2(8, 16);
const vec2 UNKNOWN_CHAR = vec2(15, 5) * CHAR_SIZE;

// TODO this definitely doesn't have to be hardcoded
const vec2 CHARS[] = vec2[](
	// ctrl chars
	UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR,
	vec2(0, 0) * CHAR_SIZE,
	vec2(1, 0) * CHAR_SIZE,
	vec2(2, 0) * CHAR_SIZE,
	vec2(3, 0) * CHAR_SIZE,
	vec2(4, 0) * CHAR_SIZE,
	vec2(5, 0) * CHAR_SIZE,
	vec2(6, 0) * CHAR_SIZE,
	vec2(7, 0) * CHAR_SIZE,
	vec2(8, 0) * CHAR_SIZE,
	vec2(9, 0) * CHAR_SIZE,
	vec2(10, 0) * CHAR_SIZE,
	vec2(11, 0) * CHAR_SIZE,
	vec2(12, 0) * CHAR_SIZE,
	vec2(13, 0) * CHAR_SIZE,
	vec2(14, 0) * CHAR_SIZE,
	vec2(15, 0) * CHAR_SIZE,
	vec2(0, 1) * CHAR_SIZE,
	vec2(1, 1) * CHAR_SIZE,
	vec2(2, 1) * CHAR_SIZE,
	vec2(3, 1) * CHAR_SIZE,
	vec2(4, 1) * CHAR_SIZE,
	vec2(5, 1) * CHAR_SIZE,
	vec2(6, 1) * CHAR_SIZE,
	vec2(7, 1) * CHAR_SIZE,
	vec2(8, 1) * CHAR_SIZE,
	vec2(9, 1) * CHAR_SIZE,
	vec2(10, 1) * CHAR_SIZE,
	vec2(11, 1) * CHAR_SIZE,
	vec2(12, 1) * CHAR_SIZE,
	vec2(13, 1) * CHAR_SIZE,
	vec2(14, 1) * CHAR_SIZE,
	vec2(15, 1) * CHAR_SIZE,
	vec2(0, 2) * CHAR_SIZE,
	vec2(1, 2) * CHAR_SIZE,
	vec2(2, 2) * CHAR_SIZE,
	vec2(3, 2) * CHAR_SIZE,
	vec2(4, 2) * CHAR_SIZE,
	vec2(5, 2) * CHAR_SIZE,
	vec2(6, 2) * CHAR_SIZE,
	vec2(7, 2) * CHAR_SIZE,
	vec2(8, 2) * CHAR_SIZE,
	vec2(9, 2) * CHAR_SIZE,
	vec2(10, 2) * CHAR_SIZE,
	vec2(11, 2) * CHAR_SIZE,
	vec2(12, 2) * CHAR_SIZE,
	vec2(13, 2) * CHAR_SIZE,
	vec2(14, 2) * CHAR_SIZE,
	vec2(15, 2) * CHAR_SIZE,
	vec2(0, 3) * CHAR_SIZE,
	vec2(1, 3) * CHAR_SIZE,
	vec2(2, 3) * CHAR_SIZE,
	vec2(3, 3) * CHAR_SIZE,
	vec2(4, 3) * CHAR_SIZE,
	vec2(5, 3) * CHAR_SIZE,
	vec2(6, 3) * CHAR_SIZE,
	vec2(7, 3) * CHAR_SIZE,
	vec2(8, 3) * CHAR_SIZE,
	vec2(9, 3) * CHAR_SIZE,
	vec2(10, 3) * CHAR_SIZE,
	vec2(11, 3) * CHAR_SIZE,
	vec2(12, 3) * CHAR_SIZE,
	vec2(13, 3) * CHAR_SIZE,
	vec2(14, 3) * CHAR_SIZE,
	vec2(15, 3) * CHAR_SIZE,
	vec2(0, 4) * CHAR_SIZE,
	vec2(1, 4) * CHAR_SIZE,
	vec2(2, 4) * CHAR_SIZE,
	vec2(3, 4) * CHAR_SIZE,
	vec2(4, 4) * CHAR_SIZE,
	vec2(5, 4) * CHAR_SIZE,
	vec2(6, 4) * CHAR_SIZE,
	vec2(7, 4) * CHAR_SIZE,
	vec2(8, 4) * CHAR_SIZE,
	vec2(9, 4) * CHAR_SIZE,
	vec2(10, 4) * CHAR_SIZE,
	vec2(11, 4) * CHAR_SIZE,
	vec2(12, 4) * CHAR_SIZE,
	vec2(13, 4) * CHAR_SIZE,
	vec2(14, 4) * CHAR_SIZE,
	vec2(15, 4) * CHAR_SIZE,
	vec2(0, 5) * CHAR_SIZE,
	vec2(1, 5) * CHAR_SIZE,
	vec2(2, 5) * CHAR_SIZE,
	vec2(3, 5) * CHAR_SIZE,
	vec2(4, 5) * CHAR_SIZE,
	vec2(5, 5) * CHAR_SIZE,
	vec2(6, 5) * CHAR_SIZE,
	vec2(7, 5) * CHAR_SIZE,
	vec2(8, 5) * CHAR_SIZE,
	vec2(9, 5) * CHAR_SIZE,
	vec2(10, 5) * CHAR_SIZE,
	vec2(11, 5) * CHAR_SIZE,
	vec2(12, 5) * CHAR_SIZE,
	vec2(13, 5) * CHAR_SIZE,
	vec2(14, 5) * CHAR_SIZE,
	// latin extended
	UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR
);

layout(location = 0) in vec2 fs_base_uv;
layout(location = 1) flat in int fs_char;

layout(location = 0) out vec4 frag_color;

uniform sampler2D u_atlas_texture;

void main()
{
	vec2 uv = (CHARS[fs_char] + fs_base_uv) / IMAGE_SIZE;
	frag_color = texture(u_atlas_texture, uv);
}
