struct Vert_Input {
	@location(0) position: vec2f,
	@location(1) uv: vec2f,
	@location(2) char: i32,
}

struct Vert_Output {
	@builtin(position) position: vec4f,
	@location(0) base_uv: vec2f,
	@location(1) @interpolate(flat) char: i32,
}

struct Frag_Input {
	@location(0) base_uv: vec2f,
	@location(1) char: i32,
}

struct Frag_Output {
	@location(0) color: vec4f,
}

@vertex
fn main_vert(in: Vert_Input) -> Vert_Output {
	var out = Vert_Output();
	out.position = vec4f(in.position, 0, 1);
	out.base_uv = in.uv;
	out.char = in.char;
	return out;
}

@group(0) @binding(0)
var u_atlas_texture: texture_2d<f32>;
@group(0) @binding(1)
var u_atlas_sampler: sampler;

@fragment
fn main_frag(in: Frag_Input) -> Frag_Output {
	// let uv = (CHARS[in.char] + in.base_uv) / IMAGE_SIZE;

	// var out = Frag_Output();
	// out.color = textureSample(u_atlas_texture, u_atlas_sampler, uv);
	// return out;
	return Frag_Output(vec4f(1, 0, 0, 1));
}

// hardcoding my beloved
const IMAGE_SIZE = vec2f(128, 96);
const CHAR_SIZE = vec2f(8, 16);
const UNKNOWN_CHAR = vec2f(15, 5) * CHAR_SIZE;
// TODO this definitely doesn't have to be hardcoded
const CHARS = array(
	// ctrl chars
	UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR,
	vec2f(0, 0) * CHAR_SIZE,
	vec2f(1, 0) * CHAR_SIZE,
	vec2f(2, 0) * CHAR_SIZE,
	vec2f(3, 0) * CHAR_SIZE,
	vec2f(4, 0) * CHAR_SIZE,
	vec2f(5, 0) * CHAR_SIZE,
	vec2f(6, 0) * CHAR_SIZE,
	vec2f(7, 0) * CHAR_SIZE,
	vec2f(8, 0) * CHAR_SIZE,
	vec2f(9, 0) * CHAR_SIZE,
	vec2f(10, 0) * CHAR_SIZE,
	vec2f(11, 0) * CHAR_SIZE,
	vec2f(12, 0) * CHAR_SIZE,
	vec2f(13, 0) * CHAR_SIZE,
	vec2f(14, 0) * CHAR_SIZE,
	vec2f(15, 0) * CHAR_SIZE,
	vec2f(0, 1) * CHAR_SIZE,
	vec2f(1, 1) * CHAR_SIZE,
	vec2f(2, 1) * CHAR_SIZE,
	vec2f(3, 1) * CHAR_SIZE,
	vec2f(4, 1) * CHAR_SIZE,
	vec2f(5, 1) * CHAR_SIZE,
	vec2f(6, 1) * CHAR_SIZE,
	vec2f(7, 1) * CHAR_SIZE,
	vec2f(8, 1) * CHAR_SIZE,
	vec2f(9, 1) * CHAR_SIZE,
	vec2f(10, 1) * CHAR_SIZE,
	vec2f(11, 1) * CHAR_SIZE,
	vec2f(12, 1) * CHAR_SIZE,
	vec2f(13, 1) * CHAR_SIZE,
	vec2f(14, 1) * CHAR_SIZE,
	vec2f(15, 1) * CHAR_SIZE,
	vec2f(0, 2) * CHAR_SIZE,
	vec2f(1, 2) * CHAR_SIZE,
	vec2f(2, 2) * CHAR_SIZE,
	vec2f(3, 2) * CHAR_SIZE,
	vec2f(4, 2) * CHAR_SIZE,
	vec2f(5, 2) * CHAR_SIZE,
	vec2f(6, 2) * CHAR_SIZE,
	vec2f(7, 2) * CHAR_SIZE,
	vec2f(8, 2) * CHAR_SIZE,
	vec2f(9, 2) * CHAR_SIZE,
	vec2f(10, 2) * CHAR_SIZE,
	vec2f(11, 2) * CHAR_SIZE,
	vec2f(12, 2) * CHAR_SIZE,
	vec2f(13, 2) * CHAR_SIZE,
	vec2f(14, 2) * CHAR_SIZE,
	vec2f(15, 2) * CHAR_SIZE,
	vec2f(0, 3) * CHAR_SIZE,
	vec2f(1, 3) * CHAR_SIZE,
	vec2f(2, 3) * CHAR_SIZE,
	vec2f(3, 3) * CHAR_SIZE,
	vec2f(4, 3) * CHAR_SIZE,
	vec2f(5, 3) * CHAR_SIZE,
	vec2f(6, 3) * CHAR_SIZE,
	vec2f(7, 3) * CHAR_SIZE,
	vec2f(8, 3) * CHAR_SIZE,
	vec2f(9, 3) * CHAR_SIZE,
	vec2f(10, 3) * CHAR_SIZE,
	vec2f(11, 3) * CHAR_SIZE,
	vec2f(12, 3) * CHAR_SIZE,
	vec2f(13, 3) * CHAR_SIZE,
	vec2f(14, 3) * CHAR_SIZE,
	vec2f(15, 3) * CHAR_SIZE,
	vec2f(0, 4) * CHAR_SIZE,
	vec2f(1, 4) * CHAR_SIZE,
	vec2f(2, 4) * CHAR_SIZE,
	vec2f(3, 4) * CHAR_SIZE,
	vec2f(4, 4) * CHAR_SIZE,
	vec2f(5, 4) * CHAR_SIZE,
	vec2f(6, 4) * CHAR_SIZE,
	vec2f(7, 4) * CHAR_SIZE,
	vec2f(8, 4) * CHAR_SIZE,
	vec2f(9, 4) * CHAR_SIZE,
	vec2f(10, 4) * CHAR_SIZE,
	vec2f(11, 4) * CHAR_SIZE,
	vec2f(12, 4) * CHAR_SIZE,
	vec2f(13, 4) * CHAR_SIZE,
	vec2f(14, 4) * CHAR_SIZE,
	vec2f(15, 4) * CHAR_SIZE,
	vec2f(0, 5) * CHAR_SIZE,
	vec2f(1, 5) * CHAR_SIZE,
	vec2f(2, 5) * CHAR_SIZE,
	vec2f(3, 5) * CHAR_SIZE,
	vec2f(4, 5) * CHAR_SIZE,
	vec2f(5, 5) * CHAR_SIZE,
	vec2f(6, 5) * CHAR_SIZE,
	vec2f(7, 5) * CHAR_SIZE,
	vec2f(8, 5) * CHAR_SIZE,
	vec2f(9, 5) * CHAR_SIZE,
	vec2f(10, 5) * CHAR_SIZE,
	vec2f(11, 5) * CHAR_SIZE,
	vec2f(12, 5) * CHAR_SIZE,
	vec2f(13, 5) * CHAR_SIZE,
	vec2f(14, 5) * CHAR_SIZE,
	// latin extended
	UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR, UNKNOWN_CHAR,
);
